version: "3"
services:

  ca_auth_db:
    image: postgres:latest
    container_name: ca_auth_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ca_auth
      POSTGRES_USER: thecharancj
      POSTGRES_PASSWORD: TheCharanCJ123

  ca_auth:
    image: charanleads/ca_auth:latest
    # build:
    #   context: ./ca_auth
    #   dockerfile: Dockerfile
    container_name: ca_auth
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - ca_auth_db

  ca_app_db:
    image: postgres:latest
    container_name: ca_app_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ca_app
      POSTGRES_USER: thecharancj
      POSTGRES_PASSWORD: TheCharanCJ123

  ca_app:
    image: charanleads/ca_app:latest
    # build:
    #   context: ./ca_app
    #   dockerfile: Dockerfile
    container_name: ca_app
    ports:
      - "5000:5000"
    depends_on:
      - ca_app_db
    env_file:
      - .env

  ca_app_redis:
    image: redis:latest
    container_name: ca_app_redis
    ports:
      - "6379:6379"

  ca_app_celery_worker:
    image: charanleads/ca_app:latest
    # build:
    #   context: ./ca_app
    #   dockerfile: Dockerfile
    command: celery -A app.celery_app:app worker --loglevel=info
    depends_on:
      - ca_app
      - ca_app_redis
    env_file:
      - .env

  ca_apps_nginx:
    image: nginx
    container_name: ca_apps_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ca_auth
      - ca_app
